// @flow

export default Object.freeze({
  colors: {
    primaryA: '#000000',
    primaryB: '#FFFFFF',
    primary: '#000000',
    primary50: '#F6F6F6',
    primary100: '#EEEEEE',
    primary200: '#E2E2E2',
    primary300: '#CBCBCB',
    primary400: '#AFAFAF',
    primary500: '#757575',
    primary600: '#545454',
    primary700: '#333333',
    accent: '#276EF1',
    accent50: '#EDF3FD',
    accent100: '#D4E2FC',
    accent200: '#9FBFF8',
    accent300: '#5A90F4',
    accent400: '#276EF1',
    accent500: '#1D53B7',
    accent600: '#174291',
    accent700: '#0F2C60',
    negative: '#D44333',
    negative50: '#FBEFEE',
    negative100: '#F6D9D6',
    negative200: '#ECACA5',
    negative300: '#DE7063',
    negative400: '#D44333',
    negative500: '#A13226',
    negative600: '#7F281E',
    negative700: '#541A14',
    warning: '#FFC043',
    warning50: '#FFF9EF',
    warning100: '#FFF2D9',
    warning200: '#FFE3AC',
    warning300: '#FFCF70',
    warning400: '#FFC043',
    warning500: '#C19132',
    warning600: '#997328',
    warning700: '#664C1A',
    positive: '#21A453',
    positive50: '#F0FAF3',
    positive100: '#CFF3DD',
    positive200: '#9EE2B8',
    positive300: '#43BF75',
    positive400: '#21A453',
    positive500: '#09863D',
    positive600: '#156A36',
    positive700: '#0D4020',
    white: '#FFFFFF',
    black: '#000000',
    mono100: '#FFFFFF',
    mono200: '#F6F6F6',
    mono300: '#EEEEEE',
    mono400: '#E2E2E2',
    mono500: '#CBCBCB',
    mono600: '#AFAFAF',
    mono700: '#757575',
    mono800: '#545454',
    mono900: '#333333',
    mono1000: '#000000',
    rating200: '#FFE3AC',
    rating400: '#FFC043',
    buttonPrimaryFill: '#000000',
    buttonPrimaryText: '#FFFFFF',
    buttonPrimaryHover: '#333333',
    buttonPrimaryActive: '#545454',
    buttonPrimarySelectedFill: '#545454',
    buttonPrimarySelectedText: '#FFFFFF',
    buttonPrimarySpinnerForeground: '#F6F6F6',
    buttonPrimarySpinnerBackground: '#757575',
    buttonSecondaryFill: '#EEEEEE',
    buttonSecondaryText: '#000000',
    buttonSecondaryHover: '#E2E2E2',
    buttonSecondaryActive: '#CBCBCB',
    buttonSecondarySelectedFill: '#CBCBCB',
    buttonSecondarySelectedText: '#000000',
    buttonSecondarySpinnerForeground: '#333333',
    buttonSecondarySpinnerBackground: '#CBCBCB',
    buttonTertiaryFill: 'transparent',
    buttonTertiaryText: '#000000',
    buttonTertiaryHover: '#F6F6F6',
    buttonTertiaryActive: '#EEEEEE',
    buttonTertiarySelectedFill: '#EEEEEE',
    buttonTertiarySelectedText: '#000000',
    buttonTertiarySpinnerForeground: '#333333',
    buttonTertiarySpinnerBackground: '#CBCBCB',
    buttonMinimalFill: 'transparent',
    buttonMinimalText: '#000000',
    buttonMinimalHover: '#F6F6F6',
    buttonMinimalActive: '#EEEEEE',
    buttonMinimalSelectedFill: '#EEEEEE',
    buttonMinimalSelectedText: '#000000',
    buttonMinimalSpinnerForeground: '#333333',
    buttonMinimalSpinnerBackground: '#CBCBCB',
    buttonDisabledFill: '#F6F6F6',
    buttonDisabledText: '#AFAFAF',
    buttonDisabledSpinnerForeground: '#AFAFAF',
    buttonDisabledSpinnerBackground: '#E2E2E2',
    breadcrumbsText: '#333333',
    breadcrumbsSeparatorFill: '#757575',
    datepickerBackground: '#FFFFFF',
    datepickerDayFont: '#000000',
    datepickerDayFontDisabled: '#CBCBCB',
    datepickerDayPseudoSelected: '#EEEEEE',
    datepickerDayPseudoHighlighted: '#E2E2E2',
    calendarBackground: '#FFFFFF',
    calendarForeground: '#000000',
    calendarForegroundDisabled: '#CBCBCB',
    calendarHeaderBackground: '#000000',
    calendarHeaderForeground: '#FFFFFF',
    calendarHeaderBackgroundActive: '#333333',
    calendarHeaderForegroundDisabled: '#757575',
    calendarDayBackgroundPseudoSelected: '#EEEEEE',
    calendarDayForegroundPseudoSelected: '#000000',
    calendarDayBackgroundPseudoSelectedHighlighted: '#E2E2E2',
    calendarDayForegroundPseudoSelectedHighlighted: '#000000',
    calendarDayBackgroundSelected: '#FFFFFF',
    calendarDayForegroundSelected: '#000000',
    calendarDayBackgroundSelectedHighlighted: '#000000',
    calendarDayForegroundSelectedHighlighted: '#FFFFFF',
    fileUploaderBackgroundColor: '#F6F6F6',
    fileUploaderBackgroundColorActive: '#F6F6F6',
    fileUploaderBorderColorActive: '#000000',
    fileUploaderBorderColorDefault: '#CBCBCB',
    fileUploaderMessageColor: '#AFAFAF',
    linkText: '#000000',
    linkVisited: '#333333',
    linkHover: '#545454',
    linkActive: '#757575',
    listHeaderFill: '#FFFFFF',
    listBodyFill: '#F6F6F6',
    listIconFill: '#CBCBCB',
    listBorder: '#CBCBCB',
    progressStepsCompletedText: '#FFFFFF',
    progressStepsCompletedFill: '#000000',
    progressStepsActiveText: '#FFFFFF',
    progressStepsActiveFill: '#000000',
    progressStepsIconActiveFill: '#000000',
    toggleFill: '#FFFFFF',
    toggleFillChecked: '#000000',
    toggleFillDisabled: '#AFAFAF',
    toggleTrackFill: '#E2E2E2',
    toggleTrackFillDisabled: '#EEEEEE',
    tickFill: '#FFFFFF',
    tickFillHover: '#F6F6F6',
    tickFillActive: '#EEEEEE',
    tickFillSelected: '#000000',
    tickFillSelectedHover: '#333333',
    tickFillSelectedHoverActive: '#545454',
    tickFillError: '#FBEFEE',
    tickFillErrorHover: '#F6D9D6',
    tickFillErrorHoverActive: '#ECACA5',
    tickFillErrorSelected: '#D44333',
    tickFillErrorSelectedHover: '#A13226',
    tickFillErrorSelectedHoverActive: '#7F281E',
    tickFillDisabled: '#AFAFAF',
    tickBorder: '#757575',
    tickBorderError: '#D44333',
    tickMarkFill: '#FFFFFF',
    tickMarkFillError: '#FFFFFF',
    tickMarkFillDisabled: '#FFFFFF',
    sliderTrackFill: '#E2E2E2',
    sliderTrackFillHover: '#CBCBCB',
    sliderTrackFillActive: '#AFAFAF',
    sliderTrackFillSelected: '#000000',
    sliderTrackFillSelectedHover: '#000000',
    sliderTrackFillSelectedActive: '#757575',
    sliderTrackFillDisabled: '#EEEEEE',
    sliderHandleFill: '#FFFFFF',
    sliderHandleFillHover: '#FFFFFF',
    sliderHandleFillActive: '#FFFFFF',
    sliderHandleFillSelected: '#FFFFFF',
    sliderHandleFillSelectedHover: '#FFFFFF',
    sliderHandleFillSelectedActive: '#FFFFFF',
    sliderHandleFillDisabled: '#CBCBCB',
    sliderHandleInnerFill: '#E2E2E2',
    sliderHandleInnerFillDisabled: '#E2E2E2',
    sliderHandleInnerFillSelectedHover: '#000000',
    sliderHandleInnerFillSelectedActive: '#757575',
    sliderBorder: '#CBCBCB',
    sliderBorderHover: '#000000',
    sliderBorderDisabled: '#AFAFAF',
    inputBorder: '#EEEEEE',
    inputFill: '#EEEEEE',
    inputFillError: '#FBEFEE',
    inputFillDisabled: '#F6F6F6',
    inputFillActive: '#F6F6F6',
    inputFillPositive: '#F0FAF3',
    inputTextDisabled: '#AFAFAF',
    inputBorderError: '#ECACA5',
    inputBorderPositive: '#9EE2B8',
    inputEnhancerFill: '#EEEEEE',
    inputEnhancerFillDisabled: '#EEEEEE',
    inputEnhancerTextDisabled: '#AFAFAF',
    menuFill: '#FFFFFF',
    menuFillHover: '#F6F6F6',
    menuFontDefault: '#545454',
    menuFontDisabled: '#CBCBCB',
    menuFontHighlighted: '#000000',
    menuFontSelected: '#000000',
    modalCloseColor: '#000000',
    modalCloseColorHover: '#545454',
    modalCloseColorFocus: '#545454',
    paginationTriangleDown: '#545454',
    headerNavigationFill: 'transparent',
    tabBarFill: '#F6F6F6',
    tabColor: '#545454',
    notificationPrimaryBackground: '#F6F6F6',
    notificationPrimaryText: '#757575',
    notificationInfoBackground: '#EDF3FD',
    notificationInfoText: '#1D53B7',
    notificationPositiveBackground: '#F0FAF3',
    notificationPositiveText: '#09863D',
    notificationWarningBackground: '#FFF9EF',
    notificationWarningText: '#C19132',
    notificationNegativeBackground: '#FBEFEE',
    notificationNegativeText: '#A13226',
    tagSolidRampUnit: '400',
    tagSolidHoverRampUnit: '50',
    tagSolidActiveRampUnit: '100',
    tagSolidDisabledRampUnit: '50',
    tagSolidFontRampUnit: '50',
    tagSolidFontHoverRampUnit: '500',
    tagLightRampUnit: '50',
    tagLightHoverRampUnit: '100',
    tagLightActiveRampUnit: '100',
    tagLightDisabledRampUnit: '50',
    tagLightFontRampUnit: '500',
    tagLightFontHoverRampUnit: '500',
    tagOutlinedRampUnit: '400',
    tagOutlinedHoverRampUnit: '500',
    tagOutlinedActiveRampUnit: '600',
    tagOutlinedDisabledRampUnit: '50',
    tagOutlinedFontRampUnit: '500',
    tagOutlinedFontHoverRampUnit: '50',
    tagFontDisabledRampUnit: '200',
    tagNeutralSolidBackground: '#333333',
    tagNeutralSolidHover: '#EEEEEE',
    tagNeutralSolidActive: '#E2E2E2',
    tagNeutralSolidDisabled: '#F6F6F6',
    tagNeutralSolidFont: '#FFFFFF',
    tagNeutralSolidFontHover: '#333333',
    tagNeutralLightBackground: '#EEEEEE',
    tagNeutralLightHover: '#EEEEEE',
    tagNeutralLightActive: '#E2E2E2',
    tagNeutralLightDisabled: '#F6F6F6',
    tagNeutralLightFont: '#333333',
    tagNeutralLightFontHover: '#333333',
    tagNeutralOutlinedBackground: '#333333',
    tagNeutralOutlinedHover: '#545454',
    tagNeutralOutlinedActive: '#333333',
    tagNeutralOutlinedDisabled: '#F6F6F6',
    tagNeutralOutlinedFont: '#333333',
    tagNeutralOutlinedFontHover: '#F6F6F6',
    tagNeutralFontDisabled: '#CBCBCB',
    tagPrimarySolidBackground: '#000000',
    tagPrimarySolidHover: '#EEEEEE',
    tagPrimarySolidActive: '#E2E2E2',
    tagPrimarySolidDisabled: '#F6F6F6',
    tagPrimarySolidFont: '#F6F6F6',
    tagPrimarySolidFontHover: '#333333',
    tagPrimaryLightBackground: '#F6F6F6',
    tagPrimaryLightHover: '#EEEEEE',
    tagPrimaryLightActive: '#EEEEEE',
    tagPrimaryLightDisabled: '#F6F6F6',
    tagPrimaryLightFont: '#757575',
    tagPrimaryLightFontHover: '#757575',
    tagPrimaryOutlinedBackground: '#000000',
    tagPrimaryOutlinedHover: '#333333',
    tagPrimaryOutlinedActive: '#545454',
    tagPrimaryOutlinedDisabled: '#F6F6F6',
    tagPrimaryOutlinedFont: '#000000',
    tagPrimaryOutlinedFontHover: '#F6F6F6',
    tagPrimaryFontDisabled: '#AFAFAF',
    tagAccentSolidBackground: '#276EF1',
    tagAccentSolidHover: '#EDF3FD',
    tagAccentSolidActive: '#D4E2FC',
    tagAccentSolidDisabled: '#EDF3FD',
    tagAccentSolidFont: '#EDF3FD',
    tagAccentSolidFontHover: '#1D53B7',
    tagAccentLightBackground: '#EDF3FD',
    tagAccentLightHover: '#D4E2FC',
    tagAccentLightActive: '#D4E2FC',
    tagAccentLightDisabled: '#EDF3FD',
    tagAccentLightFont: '#1D53B7',
    tagAccentLightFontHover: '#1D53B7',
    tagAccentOutlinedBackground: '#276EF1',
    tagAccentOutlinedHover: '#1D53B7',
    tagAccentOutlinedActive: '#174291',
    tagAccentOutlinedDisabled: '#EDF3FD',
    tagAccentOutlinedFont: '#1D53B7',
    tagAccentOutlinedFontHover: '#EDF3FD',
    tagAccentFontDisabled: '#9FBFF8',
    tagPositiveSolidBackground: '#21A453',
    tagPositiveSolidHover: '#F0FAF3',
    tagPositiveSolidActive: '#CFF3DD',
    tagPositiveSolidDisabled: '#F0FAF3',
    tagPositiveSolidFont: '#F0FAF3',
    tagPositiveSolidFontHover: '#09863D',
    tagPositiveLightBackground: '#F0FAF3',
    tagPositiveLightHover: '#CFF3DD',
    tagPositiveLightActive: '#CFF3DD',
    tagPositiveLightDisabled: '#F0FAF3',
    tagPositiveLightFont: '#09863D',
    tagPositiveLightFontHover: '#09863D',
    tagPositiveOutlinedBackground: '#21A453',
    tagPositiveOutlinedHover: '#09863D',
    tagPositiveOutlinedActive: '#156A36',
    tagPositiveOutlinedDisabled: '#F0FAF3',
    tagPositiveOutlinedFont: '#09863D',
    tagPositiveOutlinedFontHover: '#F0FAF3',
    tagPositiveFontDisabled: '#9EE2B8',
    tagWarningSolidBackground: '#FFC043',
    tagWarningSolidHover: '#FFF9EF',
    tagWarningSolidActive: '#FFF2D9',
    tagWarningSolidDisabled: '#FFF9EF',
    tagWarningSolidFont: '#664C1A',
    tagWarningSolidFontHover: '#C19132',
    tagWarningLightBackground: '#FFF9EF',
    tagWarningLightHover: '#FFF2D9',
    tagWarningLightActive: '#FFF2D9',
    tagWarningLightDisabled: '#FFF9EF',
    tagWarningLightFont: '#C19132',
    tagWarningLightFontHover: '#C19132',
    tagWarningOutlinedBackground: '#FFCF70',
    tagWarningOutlinedHover: '#C19132',
    tagWarningOutlinedActive: '#997328',
    tagWarningOutlinedDisabled: '#FFF2D9',
    tagWarningOutlinedFont: '#997328',
    tagWarningOutlinedFontHover: '#FFF9EF',
    tagWarningFontDisabled: '#FFCF70',
    tagNegativeSolidBackground: '#D44333',
    tagNegativeSolidHover: '#FBEFEE',
    tagNegativeSolidActive: '#F6D9D6',
    tagNegativeSolidDisabled: '#FBEFEE',
    tagNegativeSolidFont: '#FBEFEE',
    tagNegativeSolidFontHover: '#A13226',
    tagNegativeLightBackground: '#FBEFEE',
    tagNegativeLightHover: '#F6D9D6',
    tagNegativeLightActive: '#F6D9D6',
    tagNegativeLightDisabled: '#FBEFEE',
    tagNegativeLightFont: '#A13226',
    tagNegativeLightFontHover: '#A13226',
    tagNegativeOutlinedBackground: '#D44333',
    tagNegativeOutlinedHover: '#A13226',
    tagNegativeOutlinedActive: '#7F281E',
    tagNegativeOutlinedDisabled: '#FBEFEE',
    tagNegativeOutlinedFont: '#A13226',
    tagNegativeOutlinedFontHover: '#FBEFEE',
    tagNegativeFontDisabled: '#ECACA5',
    tableHeadBackgroundColor: '#FFFFFF',
    tableBackground: '#FFFFFF',
    tableStripedBackground: '#F6F6F6',
    tableFilter: '#AFAFAF',
    tableFilterHeading: '#757575',
    tableFilterBackground: '#FFFFFF',
    tableFilterFooterBackground: '#F6F6F6',
    toastText: '#FFFFFF',
    toastPrimaryBackground: '#757575',
    toastInfoBackground: '#1D53B7',
    toastPositiveBackground: '#09863D',
    toastWarningBackground: '#C19132',
    toastNegativeBackground: '#A13226',
    spinnerTrackFill: '#333333',
    progressbarTrackFill: '#333333',
    tooltipBackground: '#333333',
    tooltipText: '#FFFFFF',
    colorPrimary: '#000000',
    colorSecondary: '#545454',
    background: '#FFFFFF',
    backgroundAlt: '#FFFFFF',
    backgroundInv: '#000000',
    foreground: '#000000',
    foregroundAlt: '#545454',
    foregroundInv: '#FFFFFF',
    border: '#CBCBCB',
    borderAlt: '#AFAFAF',
    borderFocus: '#000000',
    borderError: '#D44333',
    shadowFocus: 'rgba(39, 110, 241, 0.32)',
    shadowError: 'rgba(229, 73, 55, 0.32)',
    backgroundPrimary: '#FFFFFF',
    backgroundSecondary: '#F6F6F6',
    backgroundTertiary: '#EEEEEE',
    backgroundInversePrimary: '#000000',
    backgroundInverseSecondary: '#1F1F1F',
    contentPrimary: '#000000',
    contentSecondary: '#545454',
    contentTertiary: '#757575',
    contentInversePrimary: '#FFFFFF',
    contentInverseSecondary: '#CBCBCB',
    contentInverseTertiary: '#AFAFAF',
    borderOpaque: '#E2E2E2',
    borderTransparent: 'rgba(0, 0, 0, 0.08)',
    borderSelected: '#000000',
    borderInverseOpaque: '#333333',
    borderInverseTransparent: 'rgba(255, 255, 255, 0.2)',
    borderInverseSelected: '#FFFFFF',
    backgroundStateDisabled: '#F6F6F6',
    backgroundOverlayDark: 'rgba(0, 0, 0, 0.3)',
    backgroundOverlayLight: 'rgba(0, 0, 0, 0.08)',
    backgroundAccent: '#276EF1',
    backgroundNegative: '#D44333',
    backgroundWarning: '#FFC043',
    backgroundPositive: '#21A453',
    backgroundLightAccent: '#EDF3FD',
    backgroundLightNegative: '#FBEFEE',
    backgroundLightWarning: '#FFF9EF',
    backgroundLightPositive: '#F0FAF3',
    backgroundAlwaysDark: '#000000',
    backgroundAlwaysLight: '#FFFFFF',
    contentStateDisabled: '#AFAFAF',
    contentAccent: '#276EF1',
    contentOnColor: '#FFFFFF',
    contentNegative: '#D44333',
    contentWarning: '#C19132',
    contentPositive: '#21A453',
    borderStateDisabled: '#F6F6F6',
    borderAccent: '#276EF1',
    borderAccentLight: '#9FBFF8',
    borderNegative: '#ECACA5',
    borderWarning: '#FFE3AC',
    borderPositive: '#9EE2B8',
  },
  animation: {
    timing100: '0.25s',
    timing400: '0.4s',
    timing700: '0.6s',
    timing1000: '1s',
    easeOutCurve: 'cubic-bezier(.2, .8, .4, 1)',
    easeInCurve: 'cubic-bezier(.8, .2, .6, 1)',
    easeInOutCurve: 'cubic-bezier(0.4, 0, 0.2, 1)',
  },
  breakpoints: { small: 320, medium: 600, large: 1136 },
  borders: {
    border100: {
      borderColor: 'hsla(0, 0%, 0%, 0.04)',
      borderStyle: 'solid',
      borderWidth: '1px',
    },
    border200: {
      borderColor: 'hsla(0, 0%, 0%, 0.08)',
      borderStyle: 'solid',
      borderWidth: '1px',
    },
    border300: {
      borderColor: 'hsla(0, 0%, 0%, 0.12)',
      borderStyle: 'solid',
      borderWidth: '1px',
    },
    border400: {
      borderColor: 'hsla(0, 0%, 0%, 0.16)',
      borderStyle: 'solid',
      borderWidth: '1px',
    },
    border500: {
      borderColor: 'hsla(0, 0%, 0%, 0.2)',
      borderStyle: 'solid',
      borderWidth: '1px',
    },
    border600: {
      borderColor: 'hsla(0, 0%, 0%, 0.24)',
      borderStyle: 'solid',
      borderWidth: '1px',
    },
    radius100: '2px',
    radius200: '4px',
    radius300: '8px',
    radius400: '12px',
    useRoundedCorners: true,
    buttonBorderRadius: '0px',
    inputBorderRadius: '0px',
    popoverBorderRadius: '0px',
    surfaceBorderRadius: '0px',
  },
  direction: 'auto',
  grid: {
    columns: [4, 8, 12],
    gutters: [16, 36, 36],
    margins: [16, 36, 64],
    gaps: 0,
    unit: 'px',
    maxWidth: 1280,
  },
  lighting: {
    shadow400: '0 1px 4px hsla(0, 0%, 0%, 0.16)',
    shadow500: '0 2px 8px hsla(0, 0%, 0%, 0.16)',
    shadow600: '0 4px 16px hsla(0, 0%, 0%, 0.16)',
    shadow700: '0 8px 24px hsla(0, 0%, 0%, 0.16)',
    overlay0: 'inset 0 0 0 1000px hsla(0, 0%, 0%, 0)',
    overlay100: 'inset 0 0 0 1000px hsla(0, 0%, 0%, 0.04)',
    overlay200: 'inset 0 0 0 1000px hsla(0, 0%, 0%, 0.08)',
    overlay300: 'inset 0 0 0 1000px hsla(0, 0%, 0%, 0.12)',
    overlay400: 'inset 0 0 0 1000px hsla(0, 0%, 0%, 0.16)',
    overlay500: 'inset 0 0 0 1000px hsla(0, 0%, 0%, 0.2)',
    overlay600: 'inset 0 0 0 1000px hsla(0, 0%, 0%, 0.24)',
  },
  mediaQuery: {
    small: '@media screen and (min-width: 320px)',
    medium: '@media screen and (min-width: 600px)',
    large: '@media screen and (min-width: 1136px)',
  },
  sizing: {
    scale0: '2px',
    scale100: '4px',
    scale200: '6px',
    scale300: '8px',
    scale400: '10px',
    scale500: '12px',
    scale550: '14px',
    scale600: '16px',
    scale650: '18px',
    scale700: '20px',
    scale750: '22px',
    scale800: '24px',
    scale900: '32px',
    scale1000: '40px',
    scale1200: '48px',
    scale1400: '56px',
    scale1600: '64px',
    scale2400: '96px',
    scale3200: '128px',
    scale4800: '192px',
  },
  typography: {
    font100: {
      fontFamily: 'system-ui, "Helvetica Neue", Helvetica, Arial, sans-serif',
      fontSize: '12px',
      fontWeight: 'normal',
      lineHeight: '20px',
    },
    font150: {
      fontFamily: 'system-ui, "Helvetica Neue", Helvetica, Arial, sans-serif',
      fontSize: '12px',
      fontWeight: 500,
      lineHeight: '16px',
    },
    font200: {
      fontFamily: 'system-ui, "Helvetica Neue", Helvetica, Arial, sans-serif',
      fontSize: '14px',
      fontWeight: 'normal',
      lineHeight: '20px',
    },
    font250: {
      fontFamily: 'system-ui, "Helvetica Neue", Helvetica, Arial, sans-serif',
      fontSize: '14px',
      fontWeight: 500,
      lineHeight: '16px',
    },
    font300: {
      fontFamily: 'system-ui, "Helvetica Neue", Helvetica, Arial, sans-serif',
      fontSize: '16px',
      fontWeight: 'normal',
      lineHeight: '24px',
    },
    font350: {
      fontFamily: 'system-ui, "Helvetica Neue", Helvetica, Arial, sans-serif',
      fontSize: '16px',
      fontWeight: 500,
      lineHeight: '20px',
    },
    font400: {
      fontFamily: 'system-ui, "Helvetica Neue", Helvetica, Arial, sans-serif',
      fontSize: '18px',
      fontWeight: 'normal',
      lineHeight: '28px',
    },
    font450: {
      fontFamily: 'system-ui, "Helvetica Neue", Helvetica, Arial, sans-serif',
      fontSize: '18px',
      fontWeight: 500,
      lineHeight: '24px',
    },
    font550: {
      fontFamily: 'system-ui, "Helvetica Neue", Helvetica, Arial, sans-serif',
      fontSize: '20px',
      fontWeight: 500,
      lineHeight: '28px',
    },
    font650: {
      fontFamily: 'system-ui, "Helvetica Neue", Helvetica, Arial, sans-serif',
      fontSize: '24px',
      fontWeight: 500,
      lineHeight: '32px',
    },
    font750: {
      fontFamily: 'system-ui, "Helvetica Neue", Helvetica, Arial, sans-serif',
      fontSize: '28px',
      fontWeight: 500,
      lineHeight: '36px',
    },
    font850: {
      fontFamily: 'system-ui, "Helvetica Neue", Helvetica, Arial, sans-serif',
      fontSize: '32px',
      fontWeight: 500,
      lineHeight: '40px',
    },
    font950: {
      fontFamily: 'system-ui, "Helvetica Neue", Helvetica, Arial, sans-serif',
      fontSize: '36px',
      fontWeight: 500,
      lineHeight: '44px',
    },
    font1050: {
      fontFamily: 'system-ui, "Helvetica Neue", Helvetica, Arial, sans-serif',
      fontSize: '40px',
      fontWeight: 500,
      lineHeight: '52px',
    },
    font1150: {
      fontFamily: 'system-ui, "Helvetica Neue", Helvetica, Arial, sans-serif',
      fontSize: '36px',
      fontWeight: 500,
      lineHeight: '44px',
    },
    font1250: {
      fontFamily: 'system-ui, "Helvetica Neue", Helvetica, Arial, sans-serif',
      fontSize: '44px',
      fontWeight: 500,
      lineHeight: '52px',
    },
    font1350: {
      fontFamily: 'system-ui, "Helvetica Neue", Helvetica, Arial, sans-serif',
      fontSize: '52px',
      fontWeight: 500,
      lineHeight: '64px',
    },
    font1450: {
      fontFamily: 'system-ui, "Helvetica Neue", Helvetica, Arial, sans-serif',
      fontSize: '96px',
      fontWeight: 500,
      lineHeight: '112px',
    },
    ParagraphXSmall: {
      fontFamily: 'system-ui, "Helvetica Neue", Helvetica, Arial, sans-serif',
      fontSize: '12px',
      fontWeight: 'normal',
      lineHeight: '20px',
    },
    ParagraphSmall: {
      fontFamily: 'system-ui, "Helvetica Neue", Helvetica, Arial, sans-serif',
      fontSize: '14px',
      fontWeight: 'normal',
      lineHeight: '20px',
    },
    ParagraphMedium: {
      fontFamily: 'system-ui, "Helvetica Neue", Helvetica, Arial, sans-serif',
      fontSize: '16px',
      fontWeight: 'normal',
      lineHeight: '24px',
    },
    ParagraphLarge: {
      fontFamily: 'system-ui, "Helvetica Neue", Helvetica, Arial, sans-serif',
      fontSize: '18px',
      fontWeight: 'normal',
      lineHeight: '28px',
    },
    LabelXSmall: {
      fontFamily: 'system-ui, "Helvetica Neue", Helvetica, Arial, sans-serif',
      fontSize: '12px',
      fontWeight: 500,
      lineHeight: '16px',
    },
    LabelSmall: {
      fontFamily: 'system-ui, "Helvetica Neue", Helvetica, Arial, sans-serif',
      fontSize: '14px',
      fontWeight: 500,
      lineHeight: '16px',
    },
    LabelMedium: {
      fontFamily: 'system-ui, "Helvetica Neue", Helvetica, Arial, sans-serif',
      fontSize: '16px',
      fontWeight: 500,
      lineHeight: '20px',
    },
    LabelLarge: {
      fontFamily: 'system-ui, "Helvetica Neue", Helvetica, Arial, sans-serif',
      fontSize: '18px',
      fontWeight: 500,
      lineHeight: '24px',
    },
    HeadingXSmall: {
      fontFamily: 'system-ui, "Helvetica Neue", Helvetica, Arial, sans-serif',
      fontSize: '20px',
      fontWeight: 500,
      lineHeight: '28px',
    },
    HeadingSmall: {
      fontFamily: 'system-ui, "Helvetica Neue", Helvetica, Arial, sans-serif',
      fontSize: '24px',
      fontWeight: 500,
      lineHeight: '32px',
    },
    HeadingMedium: {
      fontFamily: 'system-ui, "Helvetica Neue", Helvetica, Arial, sans-serif',
      fontSize: '28px',
      fontWeight: 500,
      lineHeight: '36px',
    },
    HeadingLarge: {
      fontFamily: 'system-ui, "Helvetica Neue", Helvetica, Arial, sans-serif',
      fontSize: '32px',
      fontWeight: 500,
      lineHeight: '40px',
    },
    HeadingXLarge: {
      fontFamily: 'system-ui, "Helvetica Neue", Helvetica, Arial, sans-serif',
      fontSize: '36px',
      fontWeight: 500,
      lineHeight: '44px',
    },
    HeadingXXLarge: {
      fontFamily: 'system-ui, "Helvetica Neue", Helvetica, Arial, sans-serif',
      fontSize: '40px',
      fontWeight: 500,
      lineHeight: '52px',
    },
    DisplayXSmall: {
      fontFamily: 'system-ui, "Helvetica Neue", Helvetica, Arial, sans-serif',
      fontSize: '36px',
      fontWeight: 500,
      lineHeight: '44px',
    },
    DisplaySmall: {
      fontFamily: 'system-ui, "Helvetica Neue", Helvetica, Arial, sans-serif',
      fontSize: '44px',
      fontWeight: 500,
      lineHeight: '52px',
    },
    DisplayMedium: {
      fontFamily: 'system-ui, "Helvetica Neue", Helvetica, Arial, sans-serif',
      fontSize: '52px',
      fontWeight: 500,
      lineHeight: '64px',
    },
    DisplayLarge: {
      fontFamily: 'system-ui, "Helvetica Neue", Helvetica, Arial, sans-serif',
      fontSize: '96px',
      fontWeight: 500,
      lineHeight: '112px',
    },
  },
  zIndex: { modal: 2000 },
});
